import React from "react";
import { Link } from "react-router-dom";
const Home = () => {
  return (
    <div className="dhiwise-navigation">
      <h1>Homepage</h1>
      <p className="headline">
        This project was generated By{" "}
        <a href="https://www.dhiwise.com">Dhiwise</a>. Quickly use below links
        to navigate through all pages.
      </p>
      <ul>
        <li>
          <Link to="/">Homepage</Link>
        </li>
        <li>
          <Link to="/coverimage">CoverImage</Link>
        </li>
        <li>
          <Link to="/font">Font</Link>
        </li>
        <li>
          <Link to="/color">Color</Link>
        </li>
        <li>
          <Link to="/posterandadvertisement">PosterandAdvertisement</Link>
        </li>
        <li>
          <Link to="/input">Input</Link>
        </li>
        <li>
          <Link to="/button">Button</Link>
        </li>
        <li>
          <Link to="/prototype">Prototype</Link>
        </li>
        <li>
          <Link to="/headerandfooter">HeaderandFooter</Link>
        </li>
        <li>
          <Link to="/card">Card</Link>
        </li>
        <li>
          <Link to="/choosingscheduleone">ChoosingScheduleOne</Link>
        </li>
        <li>
          <Link to="/choosingseats">ChoosingSeats</Link>
        </li>
        <li>
          <Link to="/confirmpayment">ConfirmPayment</Link>
        </li>
        <li>
          <Link to="/paymentsuccess">PaymentSuccess</Link>
        </li>
        <li>
          <Link to="/mytickettransactionlist">MyTicketTransactionList</Link>
        </li>
        <li>
          <Link to="/myticketactiveticket">MyTicketActiveTicket</Link>
        </li>
        <li>
          <Link to="/transactiondetail">TransactionDetail</Link>
        </li>
        <li>
          <Link to="/comingsoonmovies">ComingSoonMovies</Link>
        </li>
        <li>
          <Link to="/group14news">Group14News</Link>
        </li>
        <li>
          <Link to="/group14newsarticle">Group14NewsArticle</Link>
        </li>
        <li>
          <Link to="/group14newsvideo">Group14NewsVideo</Link>
        </li>
        <li>
          <Link to="/loginone">LoginOne</Link>
        </li>
        <li>
          <Link to="/signupfilmwill">SignUpFILMWILL</Link>
        </li>
        <li>
          <Link to="/loginphonenumberpasswordwrong">
            LoginPhoneNumberPasswordWrong
          </Link>
        </li>
        <li>
          <Link to="/signupphonenumberwrong">SignupPhoneNumberWrong</Link>
        </li>
        <li>
          <Link to="/resetpassword">ResetPassword</Link>
        </li>
        <li>
          <Link to="/homepageone">HomepageOne</Link>
        </li>
        <li>
          <Link to="/choosingscheduletwo">ChoosingScheduleTwo</Link>
        </li>
        <li>
          <Link to="/choosingseatsbeforelogin">ChoosingSeatsBeforeLogin</Link>
        </li>
        <li>
          <Link to="/choosingschedule">ChoosingSchedule</Link>
        </li>
        <li>
          <Link to="/tixidnews">TIXIDNews</Link>
        </li>
        <li>
          <Link to="/tixidnewsone">TIXIDNewsOne</Link>
        </li>
        <li>
          <Link to="/konfirmasipembayaran">KonfirmasiPembayaran</Link>
        </li>
        <li>
          <Link to="/pilihjadwalone">PilihJadwalOne</Link>
        </li>
        <li>
          <Link to="/homepagetwo">HomepageTwo</Link>
        </li>
        <li>
          <Link to="/pilihkursi">PilihKursi</Link>
        </li>
        <li>
          <Link to="/pilihjadwal">PilihJadwal</Link>
        </li>
        <li>
          <Link to="/login">Login</Link>
        </li>
        <li>
          <Link to="/daftarone">DaftarOne</Link>
        </li>
        <li>
          <Link to="/daftar">Daftar</Link>
        </li>
      </ul>
    </div>
  );
};
export default Home;
